# Generated by Django 2.2.10 on 2020-02-29 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auteur',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='creer_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_publication',
            new_name='published_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='texte',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='titre',
            new_name='title',
        ),
    ]
