# Generated by Django 2.2.10 on 2020-05-22 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='fk',
            new_name='id_comment',
        ),
    ]
