# Generated by Django 2.2.10 on 2020-05-23 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='id_comment',
            new_name='id_post',
        ),
    ]
