# Generated by Django 3.1.7 on 2021-03-10 16:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosperso',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='infosperso',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langue', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('1', 'Elementaire'), ('2', 'Indépendant'), ('3', 'Expérimenté')], max_length=20)),
                ('id_infosPerso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.infosperso')),
            ],
        ),
    ]
