# Generated by Django 3.1.7 on 2021-03-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210310_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='langue',
            name='level',
            field=models.CharField(choices=[('1', 'Elementaire'), ('2', 'Indépendant'), ('3', 'Expérimenté')], max_length=12),
        ),
    ]
