# Generated by Django 3.1.7 on 2021-03-10 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210310_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='langue',
            name='id_infosPerso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.infosperso'),
        ),
    ]
