# Generated by Django 3.1.7 on 2021-03-10 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_infosperso_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='langue',
            name='id_infosPerso',
        ),
    ]
