# Generated by Django 3.1.7 on 2021-03-10 16:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_langue_id_infosperso'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosperso',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='infosperso',
            name='hobbies',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='langue',
            name='id_infosPerso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.infosperso'),
        ),
        migrations.AlterField(
            model_name='langue',
            name='level',
            field=models.CharField(choices=[('ELEMENTAIRE', 'Elementaire'), ('INDEPENDANT', 'Indépendant'), ('EXPERIMENTE', 'Expérimenté')], max_length=12),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('ELEMENTAIRE', 'Elementaire'), ('INDEPENDANT', 'Indépendant'), ('EXPERIMENTE', 'Expérimenté')], max_length=12)),
                ('id_infosPerso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.infosperso')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(max_length=200)),
                ('id_infosPerso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.infosperso')),
            ],
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=200)),
                ('mention', models.CharField(choices=[('TRES BIEN', 'Très bien'), ('BIEN', 'Bien'), ('ASSEZ BIEN', 'Assez bien'), ('SANS', 'Sans')], max_length=30)),
                ('institution', models.CharField(max_length=200)),
                ('obtained_years', models.CharField(max_length=200)),
                ('id_infosPerso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.infosperso')),
            ],
        ),
    ]
