# Generated by Django 3.1.7 on 2021-03-10 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210310_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diplome',
            name='id_infosPerso',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='id_infosPerso',
        ),
        migrations.RemoveField(
            model_name='langue',
            name='id_infosPerso',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='id_infosPerso',
        ),
        migrations.DeleteModel(
            name='InfosPerso',
        ),
    ]
