# Generated by Django 3.1.7 on 2021-03-10 16:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210310_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfosPerso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('birthday', models.DateField()),
                ('hobbies', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='diplome',
            name='id_infosPerso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.infosperso'),
        ),
        migrations.AddField(
            model_name='experience',
            name='id_infosPerso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.infosperso'),
        ),
        migrations.AddField(
            model_name='langue',
            name='id_infosPerso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.infosperso'),
        ),
        migrations.AddField(
            model_name='skill',
            name='id_infosPerso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.infosperso'),
        ),
    ]
