# Generated by Django 3.1.7 on 2021-03-11 11:31

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210311_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosperso',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
