# Generated by Django 3.1.7 on 2021-03-11 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210311_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='id_infosPerso',
        ),
        migrations.RemoveField(
            model_name='langue',
            name='id_infosPerso',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='id_infosPerso',
        ),
        migrations.DeleteModel(
            name='Diplome',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='InfosPerso',
        ),
        migrations.DeleteModel(
            name='Langue',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
