# Generated by Django 3.1.7 on 2021-03-11 14:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0015_auto_20210311_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfosPerso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone incorrect', regex='^\\+?1?\\d{9,15}$')])),
                ('birthday', models.DateField()),
                ('hobbies', models.CharField(max_length=200)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('ELEMENTAIRE', 'Elementaire'), ('INDEPENDANT', 'Indépendant'), ('EXPERIMENTE', 'Expérimenté')], max_length=12)),
                ('id_infosPerso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.infosperso')),
            ],
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langue', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('ELEMENTAIRE', 'Elementaire'), ('INDEPENDANT', 'Indépendant'), ('EXPERIMENTE', 'Expérimenté')], max_length=12)),
                ('id_infosPerso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.infosperso')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_name', models.CharField(max_length=200)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(max_length=200)),
                ('id_infosPerso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.infosperso')),
            ],
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=200)),
                ('mention', models.CharField(choices=[('TRES BIEN', 'Très bien'), ('BIEN', 'Bien'), ('ASSEZ BIEN', 'Assez bien'), ('SANS', 'Sans')], max_length=30)),
                ('institution', models.CharField(max_length=200)),
                ('obtained_years', models.IntegerField()),
                ('id_infosPerso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.infosperso')),
            ],
        ),
    ]
