# Generated by Django 3.1.7 on 2021-03-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210311_1336'),
        ('home', '0015_auto_20210311_1314'),
    ]

    operations = [
    ]
